import path from 'node:path';
import { fileURLToPath } from 'node:url';
import fs from 'node:fs/promises';
import { loadArticles, generateSitemapXml } from './blog-content.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const articles = await loadArticles(path.join(root, 'content/blog'));
const output = `// Generated by scripts/generate-blog.mjs. Do not edit.\nimport type { BlogArticleData } from '../blog-types';\nexport const articles: BlogArticleData[] = ${JSON.stringify(articles, null, 2)};\n`;
await fs.mkdir(path.join(root, 'src/generated'), { recursive: true });
await fs.writeFile(path.join(root, 'src/generated/blog-posts.ts'), output);

const sitemapXml = generateSitemapXml(articles);
await fs.writeFile(path.join(root, 'public/sitemap.xml'), sitemapXml);

console.log(`Generated ${articles.length} Oracle blog article${articles.length === 1 ? '' : 's'} and updated public/sitemap.xml (${articles.length + 2} URLs).`);

